import { Grid, Stack, VStack } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import AccountDetailsCard from '../components/AccountDetailsCard'
import List from '../components/Banks/List'
import StandingOrder from '../components/StandingOrder'
import TransactionsTable from '../components/TransactionsTable'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='px-3 md:px-10 py-7 bg-nevlightgrey'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main>
      <Stack spacing={10}>
        <Grid templateColumns={{ sm: '1fr 1fr', md: '3fr 2fr' }} gap={6}>
          <AccountDetailsCard />
          <StandingOrder />
        </Grid>
        <List />
        <Grid templateColumns={{ sm: '1fr 1fr', md: '3fr 2fr' }} gap={6}>
          <TransactionsTable />
          <TransactionsTable />
          </Grid>
      </Stack>
    </main>

    </div>
  )
}


// Coz i don't like,
// the way that it feels
// or may be i do
// it's bitter it's sweet 
// it's messing with me

// the fear it is real...

// i've been on this train too long 
// everyone here looks so lost 
// am i like them i'm not sure
// how'd i get here, I don't know

// I can't stay.. 
// Break me away..
// I wanna get off.. 
// I can't do this no more..